# permissions for end users to edit nodepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodepool-editor-role
rules:
- apiGroups:
  - nodes.wrhb123.xyz
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.wrhb123.xyz
  resources:
  - nodepools/status
  verbs:
  - get
